-- ============================================================================
-- 005_agent_base.sql
-- Version: 1.0
-- Purpose:
--   Base operational ledger for Vera Anchor MCP / discovery agent.
--
-- Notes:
--   - Agent DB does not own Vera Core users/orgs/auth/billing.
--   - actor_ref/org_ref are external references to Core/API/MCP context.
--   - Stores operational receipts, quotes, payment attempts, MCP requests,
--     and public evidence cache records.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS agent;
CREATE SCHEMA IF NOT EXISTS utils;

-- ============================================================================
-- 1. Audit events
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  table_name TEXT NOT NULL,
  record_id UUID,
  record_key TEXT,

  action agent.audit_action_domain NOT NULL,

  old_data JSONB,
  new_data JSONB,

  actor_ref TEXT,
  org_ref TEXT,
  request_id TEXT,
  actor_db_role TEXT NOT NULL DEFAULT current_user,

  changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT agent_audit_table_name_chk CHECK (
    table_name ~ '^[a-zA-Z_][a-zA-Z0-9_]*\.[a-zA-Z_][a-zA-Z0-9_]*$'
  )
);

CREATE INDEX IF NOT EXISTS idx_agent_audit_table_changed_at
  ON agent.audit_events (table_name, changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_audit_record_id
  ON agent.audit_events (table_name, record_id)
  WHERE record_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_agent_audit_record_key
  ON agent.audit_events (table_name, record_key)
  WHERE record_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_agent_audit_actor_changed_at
  ON agent.audit_events (actor_ref, changed_at DESC)
  WHERE actor_ref IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_agent_audit_org_changed_at
  ON agent.audit_events (org_ref, changed_at DESC)
  WHERE org_ref IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_agent_audit_request_id
  ON agent.audit_events (request_id)
  WHERE request_id IS NOT NULL;


-- ============================================================================
-- 2. Actions
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.actions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  action_type agent.action_type_domain NOT NULL,
  status agent.action_status_domain NOT NULL DEFAULT 'created',

  actor_ref TEXT,
  org_ref TEXT,
  request_id TEXT,
  idempotency_key TEXT,

  quote_id UUID,
  payment_id UUID,
  receipt_id UUID,

  input_hash TEXT,
  params_hash TEXT,
  output_hash TEXT,

  core_reference_id TEXT,
  core_reference_type TEXT,

  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 3,

  error_code TEXT,
  error_message TEXT,

  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,

  CONSTRAINT agent_actions_attempts_chk CHECK (attempts >= 0),
  CONSTRAINT agent_actions_max_attempts_chk CHECK (max_attempts BETWEEN 0 AND 25),

  CONSTRAINT agent_actions_input_hash_chk CHECK (
    input_hash IS NULL OR length(input_hash) BETWEEN 32 AND 256
  ),
  CONSTRAINT agent_actions_params_hash_chk CHECK (
    params_hash IS NULL OR length(params_hash) BETWEEN 32 AND 256
  ),
  CONSTRAINT agent_actions_output_hash_chk CHECK (
    output_hash IS NULL OR length(output_hash) BETWEEN 32 AND 256
  ),
  CONSTRAINT agent_actions_idempotency_key_chk CHECK (
    idempotency_key IS NULL OR length(idempotency_key) BETWEEN 8 AND 256
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_actions_idempotency_live
  ON agent.actions (idempotency_key)
  WHERE idempotency_key IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_actions_status_created
  ON agent.actions (status, created_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_actions_actor_created
  ON agent.actions (actor_ref, created_at DESC)
  WHERE actor_ref IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_actions_org_created
  ON agent.actions (org_ref, created_at DESC)
  WHERE org_ref IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_actions_request_id
  ON agent.actions (request_id)
  WHERE request_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_actions_core_reference
  ON agent.actions (core_reference_type, core_reference_id)
  WHERE core_reference_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_actions_expiring
  ON agent.actions (expires_at)
  WHERE expires_at IS NOT NULL AND deleted_at IS NULL;


-- ============================================================================
-- 3. Quotes
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.quotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  action_id UUID REFERENCES agent.actions(id) ON DELETE SET NULL,

  status agent.quote_status_domain NOT NULL DEFAULT 'created',

  quote_kind TEXT NOT NULL DEFAULT 'proof_export',
  provider TEXT NOT NULL DEFAULT 'vera_anchor',

  amount_minor BIGINT NOT NULL,
  currency TEXT NOT NULL,
  network TEXT,

  quote_hash TEXT NOT NULL,
  quote_payload JSONB NOT NULL DEFAULT '{}'::jsonb,

  actor_ref TEXT,
  org_ref TEXT,
  request_id TEXT,
  idempotency_key TEXT,

  expires_at TIMESTAMPTZ NOT NULL,
  accepted_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,

  CONSTRAINT agent_quotes_amount_chk CHECK (amount_minor >= 0),
  CONSTRAINT agent_quotes_currency_chk CHECK (currency ~ '^[A-Z0-9_]{2,20}$'),
  CONSTRAINT agent_quotes_provider_chk CHECK (provider ~ '^[a-z][a-z0-9_:-]{1,79}$'),
  CONSTRAINT agent_quotes_kind_chk CHECK (quote_kind ~ '^[a-z][a-z0-9_:-]{1,79}$'),
  CONSTRAINT agent_quotes_hash_chk CHECK (length(quote_hash) BETWEEN 32 AND 256),
  CONSTRAINT agent_quotes_idempotency_key_chk CHECK (
    idempotency_key IS NULL OR length(idempotency_key) BETWEEN 8 AND 256
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_quotes_idempotency_live
  ON agent.quotes (idempotency_key)
  WHERE idempotency_key IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_quotes_action
  ON agent.quotes (action_id)
  WHERE action_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_quotes_status_expires
  ON agent.quotes (status, expires_at)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_quotes_actor_created
  ON agent.quotes (actor_ref, created_at DESC)
  WHERE actor_ref IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_quotes_org_created
  ON agent.quotes (org_ref, created_at DESC)
  WHERE org_ref IS NOT NULL AND deleted_at IS NULL;


-- ============================================================================
-- 4. Payment transactions
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.payment_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  action_id UUID REFERENCES agent.actions(id) ON DELETE SET NULL,
  quote_id UUID REFERENCES agent.quotes(id) ON DELETE SET NULL,

  provider TEXT NOT NULL,
  provider_payment_id TEXT,

  status agent.payment_status_domain NOT NULL DEFAULT 'created',

  amount_minor BIGINT,
  currency TEXT,
  network TEXT,

  payer_ref TEXT,
  payee_ref TEXT,

  transaction_reference TEXT,
  verification_reference TEXT,

  verification_attempts INTEGER NOT NULL DEFAULT 0,
  last_verified_at TIMESTAMPTZ,
  verified_at TIMESTAMPTZ,

  payment_hash TEXT,

  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

  actor_ref TEXT,
  org_ref TEXT,
  request_id TEXT,
  idempotency_key TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,

  CONSTRAINT agent_payment_provider_chk CHECK (provider ~ '^[a-z][a-z0-9_:-]{1,79}$'),
  CONSTRAINT agent_payment_amount_chk CHECK (amount_minor IS NULL OR amount_minor >= 0),
  CONSTRAINT agent_payment_attempts_chk CHECK (verification_attempts >= 0),
  CONSTRAINT agent_payment_currency_chk CHECK (
    currency IS NULL OR currency ~ '^[A-Z0-9_]{2,20}$'
  ),
  CONSTRAINT agent_payment_hash_chk CHECK (
    payment_hash IS NULL OR length(payment_hash) BETWEEN 32 AND 256
  ),
  CONSTRAINT agent_payment_idempotency_key_chk CHECK (
    idempotency_key IS NULL OR length(idempotency_key) BETWEEN 8 AND 256
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_payment_provider_payment_live
  ON agent.payment_transactions (provider, provider_payment_id)
  WHERE provider_payment_id IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_payment_idempotency_live
  ON agent.payment_transactions (idempotency_key)
  WHERE idempotency_key IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_payment_action
  ON agent.payment_transactions (action_id, created_at DESC)
  WHERE action_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_payment_quote
  ON agent.payment_transactions (quote_id, created_at DESC)
  WHERE quote_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_payment_status_created
  ON agent.payment_transactions (status, created_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_payment_actor_created
  ON agent.payment_transactions (actor_ref, created_at DESC)
  WHERE actor_ref IS NOT NULL AND deleted_at IS NULL;


-- ============================================================================
-- 5. Receipts
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.receipts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  action_id UUID REFERENCES agent.actions(id) ON DELETE SET NULL,
  quote_id UUID REFERENCES agent.quotes(id) ON DELETE SET NULL,
  payment_id UUID REFERENCES agent.payment_transactions(id) ON DELETE SET NULL,

  receipt_type agent.receipt_type_domain NOT NULL,
  receipt_hash TEXT NOT NULL,

  core_reference_id TEXT,
  core_reference_type TEXT,

  hcs_transaction_id TEXT,
  hcs_topic_id TEXT,
  explorer_url TEXT,

  artifact_uri TEXT,
  artifact_hash TEXT,

  payload JSONB NOT NULL DEFAULT '{}'::jsonb,

  actor_ref TEXT,
  org_ref TEXT,
  request_id TEXT,
  idempotency_key TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT agent_receipts_hash_chk CHECK (length(receipt_hash) BETWEEN 32 AND 256),
  CONSTRAINT agent_receipts_artifact_hash_chk CHECK (
    artifact_hash IS NULL OR length(artifact_hash) BETWEEN 32 AND 256
  ),
  CONSTRAINT agent_receipts_idempotency_key_chk CHECK (
    idempotency_key IS NULL OR length(idempotency_key) BETWEEN 8 AND 256
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_receipts_action_type_live
  ON agent.receipts (action_id, receipt_type)
  WHERE action_id IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_receipts_idempotency_live
  ON agent.receipts (idempotency_key)
  WHERE idempotency_key IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_receipts_hash
  ON agent.receipts (receipt_hash)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_receipts_core_reference
  ON agent.receipts (core_reference_type, core_reference_id)
  WHERE core_reference_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_receipts_hcs
  ON agent.receipts (hcs_topic_id, hcs_transaction_id)
  WHERE hcs_transaction_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_receipts_actor_created
  ON agent.receipts (actor_ref, created_at DESC)
  WHERE actor_ref IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_receipts_org_created
  ON agent.receipts (org_ref, created_at DESC)
  WHERE org_ref IS NOT NULL AND deleted_at IS NULL;


-- ============================================================================
-- 6. MCP requests
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.mcp_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  action_id UUID REFERENCES agent.actions(id) ON DELETE SET NULL,

  request_id TEXT,
  session_id TEXT,
  client_ref TEXT,

  tool_name TEXT NOT NULL,
  status agent.mcp_request_status_domain NOT NULL DEFAULT 'received',

  input_hash TEXT,
  output_hash TEXT,

  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,

  latency_ms INTEGER,

  error_code TEXT,
  error_message TEXT,

  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

  actor_ref TEXT,
  org_ref TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT agent_mcp_tool_name_chk CHECK (
    tool_name ~ '^[a-zA-Z][a-zA-Z0-9_.:-]{1,120}$'
  ),
  CONSTRAINT agent_mcp_latency_chk CHECK (
    latency_ms IS NULL OR latency_ms >= 0
  ),
  CONSTRAINT agent_mcp_input_hash_chk CHECK (
    input_hash IS NULL OR length(input_hash) BETWEEN 32 AND 256
  ),
  CONSTRAINT agent_mcp_output_hash_chk CHECK (
    output_hash IS NULL OR length(output_hash) BETWEEN 32 AND 256
  )
);

CREATE INDEX IF NOT EXISTS idx_agent_mcp_tool_created
  ON agent.mcp_requests (tool_name, created_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_mcp_status_created
  ON agent.mcp_requests (status, created_at DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_mcp_action
  ON agent.mcp_requests (action_id)
  WHERE action_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_mcp_request_id
  ON agent.mcp_requests (request_id)
  WHERE request_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_mcp_actor_created
  ON agent.mcp_requests (actor_ref, created_at DESC)
  WHERE actor_ref IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_mcp_org_created
  ON agent.mcp_requests (org_ref, created_at DESC)
  WHERE org_ref IS NOT NULL AND deleted_at IS NULL;


-- ============================================================================
-- 7. Evidence cache
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent.evidence_cache (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  cache_key TEXT NOT NULL,
  source_type TEXT NOT NULL,
  source_ref TEXT NOT NULL,

  status agent.cache_status_domain NOT NULL DEFAULT 'fresh',

  evidence_hash TEXT NOT NULL,
  evidence_payload JSONB NOT NULL DEFAULT '{}'::jsonb,

  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,

  error_code TEXT,
  error_message TEXT,

  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,

  CONSTRAINT agent_evidence_cache_key_chk CHECK (length(cache_key) BETWEEN 8 AND 512),
  CONSTRAINT agent_evidence_source_type_chk CHECK (
    source_type ~ '^[a-z][a-z0-9_:-]{1,79}$'
  ),
  CONSTRAINT agent_evidence_hash_chk CHECK (length(evidence_hash) BETWEEN 32 AND 256)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_agent_evidence_cache_key_live
  ON agent.evidence_cache (cache_key)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_evidence_source
  ON agent.evidence_cache (source_type, source_ref)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_evidence_status_expires
  ON agent.evidence_cache (status, expires_at)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_agent_evidence_fetched
  ON agent.evidence_cache (fetched_at DESC)
  WHERE deleted_at IS NULL;


-- ============================================================================
-- 8. Add circular reference FKs from actions after dependent tables exist
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_agent_actions_quote_id'
  ) THEN
    ALTER TABLE agent.actions
      ADD CONSTRAINT fk_agent_actions_quote_id
      FOREIGN KEY (quote_id)
      REFERENCES agent.quotes(id)
      ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_agent_actions_payment_id'
  ) THEN
    ALTER TABLE agent.actions
      ADD CONSTRAINT fk_agent_actions_payment_id
      FOREIGN KEY (payment_id)
      REFERENCES agent.payment_transactions(id)
      ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_agent_actions_receipt_id'
  ) THEN
    ALTER TABLE agent.actions
      ADD CONSTRAINT fk_agent_actions_receipt_id
      FOREIGN KEY (receipt_id)
      REFERENCES agent.receipts(id)
      ON DELETE SET NULL;
  END IF;
END $$;


-- ============================================================================
-- 9. Triggers
-- ============================================================================

DROP TRIGGER IF EXISTS trg_agent_actions_updated_at ON agent.actions;
CREATE TRIGGER trg_agent_actions_updated_at
BEFORE UPDATE ON agent.actions
FOR EACH ROW
EXECUTE FUNCTION utils.set_updated_at();

DROP TRIGGER IF EXISTS trg_agent_actions_audit ON agent.actions;
CREATE TRIGGER trg_agent_actions_audit
AFTER INSERT OR UPDATE OR DELETE ON agent.actions
FOR EACH ROW
EXECUTE FUNCTION utils.audit_agent_trigger();

DROP TRIGGER IF EXISTS trg_agent_quotes_updated_at ON agent.quotes;
CREATE TRIGGER trg_agent_quotes_updated_at
BEFORE UPDATE ON agent.quotes
FOR EACH ROW
EXECUTE FUNCTION utils.set_updated_at();

DROP TRIGGER IF EXISTS trg_agent_quotes_audit ON agent.quotes;
CREATE TRIGGER trg_agent_quotes_audit
AFTER INSERT OR UPDATE OR DELETE ON agent.quotes
FOR EACH ROW
EXECUTE FUNCTION utils.audit_agent_trigger();

DROP TRIGGER IF EXISTS trg_agent_payment_updated_at ON agent.payment_transactions;
CREATE TRIGGER trg_agent_payment_updated_at
BEFORE UPDATE ON agent.payment_transactions
FOR EACH ROW
EXECUTE FUNCTION utils.set_updated_at();

DROP TRIGGER IF EXISTS trg_agent_payment_audit ON agent.payment_transactions;
CREATE TRIGGER trg_agent_payment_audit
AFTER INSERT OR UPDATE OR DELETE ON agent.payment_transactions
FOR EACH ROW
EXECUTE FUNCTION utils.audit_agent_trigger();

DROP TRIGGER IF EXISTS trg_agent_receipts_audit ON agent.receipts;
CREATE TRIGGER trg_agent_receipts_audit
AFTER INSERT OR UPDATE OR DELETE ON agent.receipts
FOR EACH ROW
EXECUTE FUNCTION utils.audit_agent_trigger();

DROP TRIGGER IF EXISTS trg_agent_mcp_requests_audit ON agent.mcp_requests;
CREATE TRIGGER trg_agent_mcp_requests_audit
AFTER INSERT OR UPDATE OR DELETE ON agent.mcp_requests
FOR EACH ROW
EXECUTE FUNCTION utils.audit_agent_trigger();

DROP TRIGGER IF EXISTS trg_agent_evidence_cache_updated_at ON agent.evidence_cache;
CREATE TRIGGER trg_agent_evidence_cache_updated_at
BEFORE UPDATE ON agent.evidence_cache
FOR EACH ROW
EXECUTE FUNCTION utils.set_updated_at();

DROP TRIGGER IF EXISTS trg_agent_evidence_cache_audit ON agent.evidence_cache;
CREATE TRIGGER trg_agent_evidence_cache_audit
AFTER INSERT OR UPDATE OR DELETE ON agent.evidence_cache
FOR EACH ROW
EXECUTE FUNCTION utils.audit_agent_trigger();


-- ============================================================================
-- 10. Grants
-- ============================================================================

REVOKE ALL ON ALL TABLES IN SCHEMA agent FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA agent FROM PUBLIC;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'vera_agent_app') THEN
    GRANT SELECT, INSERT, UPDATE ON agent.actions TO vera_agent_app;
    GRANT SELECT, INSERT, UPDATE ON agent.quotes TO vera_agent_app;
    GRANT SELECT, INSERT, UPDATE ON agent.payment_transactions TO vera_agent_app;
    GRANT SELECT, INSERT, UPDATE ON agent.receipts TO vera_agent_app;
    GRANT SELECT, INSERT, UPDATE ON agent.mcp_requests TO vera_agent_app;
    GRANT SELECT, INSERT, UPDATE ON agent.evidence_cache TO vera_agent_app;

    GRANT SELECT ON agent.audit_events TO vera_agent_app;

    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA agent TO vera_agent_app;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'vera_agent_admin') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA agent TO vera_agent_admin;
    GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA agent TO vera_agent_admin;
  END IF;
END $$;